# Generated by Django 4.1.5 on 2023-11-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roda', models.CharField(choices=[('static/img/roda/pe/dianteira/preto/preto.png', 'pe_d'), ('static/img/roda/pe/traseira/preto.png', 'pe_t'), ('static/img/roda/raiada/traseira.png', 'raiada_t'), ('static/img/roda/raiada/dianteira.png', 'raiada_d')], max_length=150)),
                ('paralama', models.CharField(choices=[('static/img/roda/pe/dianteira/preto/preto.png', 'pe_preto'), ('static/img/roda/pe/dianteira/preto/vermelho.png', 'pe_vermelho'), ('static/img/roda/raiada/dianteira.png', 'rai_preto'), ('static/img/roda/raiada/paralama/vermelha.png', 'rai_preto')], max_length=150)),
                ('carenagemTraseira', models.CharField(choices=[('static/img/carenagem/traseira/carenagemTrasPreta.png', 'PRETO'), ('static/img/carenagem/traseira/carenagemTrasVerm.png', 'VERMELHO')], max_length=150)),
                ('frente', models.CharField(choices=[('static/img/frente/frente fan 22/frente fan 22 preta.png', 'F_PRETA'), ('static/img/frente/frente fan 22/frente fan 22 verm.png', 'F_VERM'), ('static/img/frente/frente titan 22/frente titan 22 preta.png', 'T_PRETA'), ('static/img/frente/frente titan 22/frente titan 22 verm.png', 'T_VERM'), ('static/img/frente/frente tw/frente tw preta.png', 'TW_PRETA'), ('static/img/frente/frente tw/frente tw verm.png', 'TW_VERMELHA')], max_length=150)),
                ('escapamento', models.CharField(choices=[('static/img/escapamento/original/escapOrigPrata.png', 'original'), ('static/img/escapamento/delata/escapDeLata.png', 'delata'), ('static/img/escapamento/delata/escapDeLataProt.png', 'delata_prot'), ('static/img/escapamento/delata/escapTorbalEstra.png', 'torbal'), ('static/img/escapamento/dore/escapDoreAzulAT.png', 'd_azul'), ('static/img/escapamento/dore/escapDoreVermAT.png', 'd_verm'), ('static/img/escapamento/dore/escapDorePretoAT.png', 'd_preto'), ('static/img/escapamento/dore/escapDorePolidoAT.png', 'd_prata')], max_length=150)),
                ('tampaMotor', models.CharField(choices=[('static/img/vazio.png', 'prata'), ('static/img/motor/tampaLateral/tampaPretaMotor.png', 'preta')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('moto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.moto')),
                ('tanque', models.CharField(choices=[('static/img/tanque/tanqueStartPreto.png', 'PRETO'), ('static/img/tanque/tanqueStartVerm.png', 'VERMELHO')], max_length=150)),
            ],
            bases=('app.moto',),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.moto')),
            ],
        ),
    ]
