# Generated by Django 4.1.5 on 2023-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='alca',
            field=models.CharField(choices=[('static/img/alca/alcaOrigPreta.png', 'preto'), ('static/img/alca/alcaOrigCromo.png', 'cromo'), ('static/img/alca/alcaAltaPreta.png', 'alta preta'), ('static/img/alca/alcaAltaCromo.png', 'alta cromo'), ('static/img/alca/churrasqueiraCromo.png', 'churrasqueira cromo'), ('static/img/alca/churrasqueiraCromoGivi.png', 'churrasqueira cromo givi'), ('static/img/alca/churrasqueiraCromoGiviBau.png', 'churrasqueira cromo givi bau'), ('static/img/alca/churrasqueiraCromoSup.png', 'churrasqueira cromo suporte'), ('static/img/alca/churrasqueiraCromoSupBau.png', 'churrasqueira cromo suporte bau'), ('static/img/alca/churrasqueiraPreta.png', 'churrasqueira preta'), ('static/img/alca/churrasqueiraPretaGivi.png', 'churrasqueira preta givi'), ('static/img/alca/churrasqueiraPretaGiviBau.png', 'churrasqueira preta givi bau'), ('static/img/alca/churrasqueiraPretaSup.png', 'churrasqueira preta suporte'), ('static/img/alca/churrasqueiraPretaSupBau.png', 'churrasqueira preta suporte bau')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moto',
            name='tanque',
            field=models.CharField(choices=[('static/img/tanque/tanqueStartPreto.png', 'PRETO'), ('static/img/tanque/tanqueStartVerm.png', 'VERMELHO')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
