# Generated by Django 4.1.5 on 2023-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='roda',
        ),
        migrations.AddField(
            model_name='moto',
            name='roda_d',
            field=models.CharField(choices=[('static/img/roda/pe/dianteira/preto/preto.png', 'pe_d'), ('static/img/roda/raiada/dianteira.png', 'raiada_d')], default=1, max_length=150, verbose_name='Roda Dianteira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moto',
            name='roda_t',
            field=models.CharField(choices=[('static/img/roda/pe/traseira/preto.png', 'pe_t'), ('static/img/roda/raiada/traseira.png', 'raiada_t')], default=1, max_length=150, verbose_name='Roda Traseira'),
            preserve_default=False,
        ),
    ]
