# Generated by Django 4.1.5 on 2023-11-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_moto_alca_moto_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='titulo',
            field=models.CharField(default=1, max_length=50, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moto',
            name='usu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
