# Generated by Django 4.1.5 on 2023-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_moto_titulo_moto_usu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='paralama',
        ),
        migrations.AlterField(
            model_name='moto',
            name='roda_d',
            field=models.CharField(choices=[('static/img/roda/pe/dianteira/preto/preto.png', 'pe dianteira paralama preto'), ('static/img/roda/pe/dianteira/preto/vermelho.png', 'pe dianteira paralama vermelho'), ('static/img/roda/raiada/dianteira.png', 'raiada diateira paralama preto'), ('static/img/roda/raiada/paralama/vermelha.png', 'raiada dianteira paralama vermelho')], max_length=150, verbose_name='Roda Dianteira'),
        ),
    ]
